  #&& wget --no-check-certificate https://tls.lab/certs/intermediate.crt \
  #    -O /etc/ssl/certs/lab-intermediate.crt \
  #    && cat /etc/ssl/certs/lab-intermediate.crt >> /etc/ssl/certs/ca-certificates.crt

services:
  gitea_sys_runner:
    image: git.lab/lab/gitea_sys_runner:latest
    depends_on: [dnsmasq_svc, caddy_svc, gitea_svc]
    build:
      dockerfile_inline: |
        FROM gitea/act_runner:latest
        RUN apk add -U nodejs
        RUN wget --no-check-certificate https://tls.lab/certs/root.crt -O /etc/ssl/certs/lab-root.crt
        RUN cat /etc/ssl/certs/lab-root.crt >> /etc/ssl/certs/ca-certificates.crt
    container_name: gitea_sys_runner
    # Required for docker in docker control.
    privileged: true
    environment:
      - CONFIG_FILE=/data/config.yaml
    # Consider an init container for the ssh keys
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/state/gitea_sys_runner/data:/data
      - /opt/imports/gitea_sys_runner/ssh:/home/root/.ssh
    restart: unless-stopped
